name: btl_nhom2_ptudcctbdd
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  cloud_firestore: ^6.2.0
  firebase_auth: ^6.3.0
  firebase_core: ^4.6.0
  firebase_storage: ^13.0.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  http: ^1.2.2
  http_parser: ^4.1.2
  image_picker: ^1.1.2
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  intl: ^0.20.2
  audioplayers: ^6.6.0
  flutter_local_notifications: ^21.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
