// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcMY15EE_KRHZvccQmV-olTyZsExIJMVE',
    appId: '1:569977301187:web:55900582bcd55a40029a76',
    messagingSenderId: '569977301187',
    projectId: 'btl-nhom2-ptudcctbdd',
    authDomain: 'btl-nhom2-ptudcctbdd.firebaseapp.com',
    storageBucket: 'btl-nhom2-ptudcctbdd.firebasestorage.app',
    measurementId: 'G-K7S5Y0FXGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPmOEyTIPgmo9mHeG9WWx6ccQ0jrdtlyU',
    appId: '1:569977301187:android:1dcf2fa887a45362029a76',
    messagingSenderId: '569977301187',
    projectId: 'btl-nhom2-ptudcctbdd',
    storageBucket: 'btl-nhom2-ptudcctbdd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_CnGpKRsJC7SRCKu9m9N81ZYTPjl9Isk',
    appId: '1:569977301187:ios:dbf420401d694dd9029a76',
    messagingSenderId: '569977301187',
    projectId: 'btl-nhom2-ptudcctbdd',
    storageBucket: 'btl-nhom2-ptudcctbdd.firebasestorage.app',
    iosClientId:
        '569977301187-c2koebtflk0msunr4hed7i1hh0g8kv92.apps.googleusercontent.com',
    iosBundleId: 'com.example.btlNhom2Ptudcctbdd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_CnGpKRsJC7SRCKu9m9N81ZYTPjl9Isk',
    appId: '1:569977301187:ios:dbf420401d694dd9029a76',
    messagingSenderId: '569977301187',
    projectId: 'btl-nhom2-ptudcctbdd',
    storageBucket: 'btl-nhom2-ptudcctbdd.firebasestorage.app',
    iosClientId:
        '569977301187-c2koebtflk0msunr4hed7i1hh0g8kv92.apps.googleusercontent.com',
    iosBundleId: 'com.example.btlNhom2Ptudcctbdd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcMY15EE_KRHZvccQmV-olTyZsExIJMVE',
    appId: '1:569977301187:web:7566ab24791f3642029a76',
    messagingSenderId: '569977301187',
    projectId: 'btl-nhom2-ptudcctbdd',
    authDomain: 'btl-nhom2-ptudcctbdd.firebaseapp.com',
    storageBucket: 'btl-nhom2-ptudcctbdd.firebasestorage.app',
    measurementId: 'G-5070WMWWT0',
  );
}
